# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-28 03:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='about',
        ),
    ]
