# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-15 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='about',
        ),
        migrations.RemoveField(
            model_name='account',
            name='college',
        ),
        migrations.RemoveField(
            model_name='account',
            name='year_in_school',
        ),
    ]
