# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_fix_str'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='about',
            field=models.TextField(blank=True, default='', help_text='tell us about your shitty professors or something'),
        ),
        migrations.AddField(
            model_name='account',
            name='college',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='year_in_school',
            field=models.CharField(blank=True, choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], default='FR', max_length=10),
        ),
    ]
