# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-28 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_account_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='about',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
