# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-03 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20170228_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='account',
            name='wait_list',
        ),
        migrations.AddField(
            model_name='account',
            name='requesting',
            field=models.ManyToManyField(related_name='requested', to='account.Account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='following',
            field=models.ManyToManyField(related_name='followers', to='account.Account'),
        ),
    ]
