# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-07 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20170303_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='account.Account'),
        ),
        migrations.AlterField(
            model_name='account',
            name='requesting',
            field=models.ManyToManyField(blank=True, related_name='requested', to='account.Account'),
        ),
    ]
