# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-19 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20170306_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='college',
            field=models.CharField(choices=[('1', 'Penn State University'), ('2', 'Temple University')], default=1, max_length=25, null=True),
        ),
    ]
