# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-21 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0042_auto_20170321_1519'),
        ('account', '0008_auto_20170319_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='attending',
            field=models.ManyToManyField(blank=True, to='Post.Post'),
        ),
    ]
