# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-21 23:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_account_attending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='attending',
        ),
    ]
