# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-24 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_remove_account_attending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='about',
            field=models.TextField(blank=True, default="Hi I'm just a cool bean", max_length=500, null=True),
        ),
    ]
