# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-24 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20170323_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='about',
            field=models.TextField(default="Hi I'm just a cool bean", max_length=500),
        ),
    ]
