# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-01 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20170323_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='organization',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
