# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-01 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('email', models.CharField(max_length=128)),
                ('confirmation_num', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('event_name', models.CharField(max_length=128)),
                ('confirmed', models.CharField(max_length=20)),
            ],
        ),
    ]
