# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-31 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=128)),
                ('confirmation_num', models.CharField(max_length=20, unique=True)),
                ('event_name', models.CharField(max_length=128)),
                ('confirmed', models.CharField(default='unconfirmed', max_length=20)),
            ],
        ),
    ]
