# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-06 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
