# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-19 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_ticket_charge_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='charge_id',
            field=models.CharField(max_length=120),
        ),
    ]
