# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 23:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=False, max_length=200)),
                ('street_address', models.CharField(default=False, max_length=200)),
                ('city', models.CharField(default=False, max_length=200)),
                ('state', models.CharField(default=False, max_length=200)),
                ('zip_code', models.IntegerField(default=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('stage', models.TimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('posted_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
