# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 23:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='stage',
        ),
    ]
