# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-21 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
