# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_remove_post_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='city',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='state',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='street_address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='zip_code',
            field=models.IntegerField(),
        ),
    ]
