# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-17 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_auto_20160715_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
