# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-17 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_auto_20160716_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(blank=True, help_text='MM/DD/YYYY', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.TimeField(blank=True, help_text='only 24 hour clocks, you can do that, right?', null=True),
        ),
    ]
