# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-21 05:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_auto_20170520_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcomment',
            name='created_at',
        ),
    ]
