# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_auto_20160528_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='city',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='post',
            name='state',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='zip_code',
            field=models.CharField(max_length=5),
        ),
    ]
