# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-17 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0004_auto_20160716_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.TimeField(blank=True, help_text='24 hour clock', null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
