# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0005_auto_20160601_0112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='posted_date',
            new_name='posted_Date',
        ),
    ]
