# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-02 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0005_auto_20170601_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_personal',
            field=models.BooleanField(default=False),
        ),
    ]
