# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 20:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import localflavor.us.models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Post', '0006_auto_20160718_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('street_address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=64)),
                ('state', localflavor.us.models.USStateField()),
                ('zip_code', models.CharField(max_length=5)),
                ('date', models.DateField(blank=True, help_text='MM/DD/YYYY', null=True)),
                ('time', models.TimeField(blank=True, help_text='24 hour clock', null=True)),
                ('description', models.TextField()),
                ('tickets_link', models.URLField()),
                ('image', stdimage.models.StdImageField(blank=True, null=True, upload_to='Post/images')),
                ('posted_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConcertComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('approved_comment', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concertcomments', to='Post.Post')),
            ],
        ),
    ]
