# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 20:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0006_auto_20160601_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='posted_Date',
            new_name='posted_date',
        ),
    ]
