# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 21:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0007_concert_concertcomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concert',
            old_name='tickets_link',
            new_name='ticket_link',
        ),
    ]
