# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0007_auto_20160601_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=''),
        ),
    ]
