# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-21 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0008_auto_20160721_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concertcomment',
            name='post',
        ),
        migrations.AddField(
            model_name='concertcomment',
            name='concert',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='concertcomments', to='Post.Concert'),
        ),
    ]
