# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-08 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0009_auto_20160721_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='latlng',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
