# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-02 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0009_post_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.TimeField(blank=True),
        ),
    ]
