# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-10 18:49
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0010_post_latlng'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('gis', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='latlng',
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='longitude/latitude'),
        ),
    ]
