# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-01 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0011_auto_20160810_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='starting_price',
            field=models.IntegerField(null=True),
        ),
    ]
