# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0012_auto_20160603_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.TimeField(default=''),
        ),
    ]
