# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-10 21:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0013_post_draft'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='concert',
            name='starting_price',
        ),
        migrations.RemoveField(
            model_name='post',
            name='draft',
        ),
        migrations.RemoveField(
            model_name='post',
            name='location',
        ),
    ]
