# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-10 21:34
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0014_auto_20160910_1705'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('gis', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='concert',
            name='starting_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='longitude/latitude'),
        ),
    ]
