# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-03 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0014_auto_20160603_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='Post/images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
