# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-25 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0016_auto_20160922_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='end_date',
            field=models.DateField(blank=True, help_text='not requiered', null=True),
        ),
    ]
