# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0016_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='post',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
