# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-29 00:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0018_survey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='entry',
            new_name='email',
        ),
    ]
