# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-20 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0019_auto_20160620_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='tags',
        ),
    ]
