# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-04 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0020_post_ticket_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(help_text='MM/DD/YYYY', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='ticket_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.TimeField(help_text='24 hour clock', null=True),
        ),
    ]
