# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-04 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0023_auto_20161004_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('NOTHING', '------'), ('MUSIC', 'Music'), ('SPORTS', 'Sports'), ('FUNDRAISERS', 'Fundraisers'), ('DANCE', 'Dance'), ('PERFORMING_ARTS', 'Performing Arts'), ('POLITICAL', 'Political'), ('CONCERTS', 'Concerts'), ('ARTS', 'Arts'), ('SCIENCE', 'Science'), ('ACADEMIC', 'Academic'), ('PROFESSIONAL', 'Professional')], default=None, max_length=250),
        ),
    ]
