# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-25 02:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0023_auto_20160624_2208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='comment',
        ),
    ]
