# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-25 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0025_auto_20160625_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Post.Category'),
        ),
    ]
