# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-05 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0026_auto_20161004_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
