# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-17 22:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0030_auto_20161005_1321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-posted_date']},
        ),
    ]
