# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-17 05:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0032_broadcast_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broadcast_email',
            options={},
        ),
        migrations.RemoveField(
            model_name='broadcast_email',
            name='from_email',
        ),
        migrations.RemoveField(
            model_name='broadcast_email',
            name='to',
        ),
    ]
