# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-25 20:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0033_auto_20160625_1621'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
