# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-17 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0033_auto_20161117_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcast_email',
            name='html_content',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='broadcast_email',
            name='text_content',
            field=models.TextField(default=None, null=True),
        ),
    ]
