# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-05 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0035_auto_20161230_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='saves',
            field=models.IntegerField(null=True),
        ),
    ]
