# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-02-28 22:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0037_auto_20170217_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='saves',
        ),
    ]
