# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0037_auto_20160627_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(to='Post.Category'),
        ),
    ]
