# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-20 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0039_post_attendees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='attendees',
            new_name='attending',
        ),
    ]
