# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0040_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='entry',
        ),
    ]
