# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0043_auto_20160628_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='entry',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
