# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0044_auto_20160628_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='entry',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name=''),
        ),
    ]
