# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0049_auto_20160628_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcomment',
            name='question',
        ),
    ]
