# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0051_auto_20160628_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventcomment',
            options={'get_latest_by': ['created_date']},
        ),
        migrations.AlterModelOptions(
            name='questioncomment',
            options={'get_latest_by': ['created_date']},
        ),
    ]
