# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0053_auto_20160628_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='entry',
            field=models.TextField(max_length=200, null=True, verbose_name=''),
        ),
    ]
