# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-07 12:34
from __future__ import unicode_literals

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0055_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Profile',
        ),
        migrations.AlterField(
            model_name='post',
            name='state',
            field=localflavor.us.models.USStateField(),
        ),
    ]
