# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-07 14:04
from __future__ import unicode_literals

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0056_auto_20160707_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photo',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='Post/images'),
        ),
    ]
