# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-08 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0057_auto_20160707_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.TimeField(blank=True, help_text='only 24 hour clocks, you can do that, right?', null=True),
        ),
    ]
