# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-09 01:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('1', 'Music'), ('2', 'Comedy'), ('3', 'Fundraisers'), ('4', 'Dance'), ('5', 'Theatre'), ('6', 'Improv'), ('12', 'Movies'), ('7', 'Debates'), ('8', 'Arts'), ('9', 'Club Event'), ('10', 'Academic'), ('11', 'Professional')], max_length=25, null=True)),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField()),
                ('image', stdimage.models.StdImageField(blank=True, null=True, upload_to='Post/images')),
                ('video', models.URLField(blank=True, null=True)),
                ('posted_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
