# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-17 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170102_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
